Implementation of ePSF and astrometry fix
spacetelescope/STScI-STIPS pull request #156
Opened 2022-06-16 15:47 UTC by gmzsebastian

This pull request is intended to be for the STIPS 2.0 release, implementing a number of changes. Mainly, the implementation of an ePSF routine that fixes previous astrometry issues. Other changes include:

- Forcing versions of specific packages to be compatible with each other.
- Inclusion of a "bright" and "extra bright" parameters to allow for larger PSFs to be generated for bright sources.
- Estimates for detector offsets for all 18 SCAs.
- Changed detector size to 4088 x 4088.
- Removed filter F149.
- Updated PHOTFNU values.
- Changed how rounding of floats is done.
- Introduction of `makePSF.py` file with all the calculations related to generating the PSF and ePSF

2022-06-24 15:15 UTC, jrhastro requested changes

2022-06-24 15:15 UTC, jrhastro commented on stips/utilities/makePSF.py
> +def interpolate_epsf(xpix, ypix, psf_array, image_size):
Define image_size/2 as its own variable.  It is used frequently and should increase readability.

2022-06-24 15:15 UTC, jrhastro commented on stips/utilities/makePSF.py
> +        min_y = max(0, round(ypix-boxsize))
These can be moved out of the loop since each parameter is fixed for a given call of place_source(), correct?

2022-06-24 15:15 UTC, jrhastro commented on stips/utilities/makePSF.py
> +            min_x = max(0, round(xpix-boxsize))
These can be moved out of the loop since each parameter is fixed for a given call of place_source(), correct?

2022-06-24 15:15 UTC, jrhastro commented on stips/utilities/makePSF.py
> +                else:
There was discussion as to whether these lines are truly necessary if the earlier lines restrict the range on the image.

2022-06-27 14:09 UTC, york-stsci commented
I'm going to take a look at the environment.yml file, and see if I can figure out what's going on, because it seems as if the checks are failing more or less entirely because the environment isn't building for some reason.

2022-07-06 14:28 UTC, york-stsci commented
The CI test failures with python 3.7 are part of removing python 3.7 support from STIPS version 2.0 I will file a cleanup PR that removes outdated tests. As such, and because the testing under python 3.8 succeeds both on GitHub and locally, I approve this PR.

The above is also a waiver for requiring passing CI tests for this particular PR. Note that STIPS will still need to have a clean set of tests for the 2.0.0 release.

2022-07-06 14:29 UTC, merged